const mongoose = require('mongoose');

const fooditemSchema = mongoose.Schema({
    ID: {
        type: String,
        required: true,
    }, 
    // custom ID number generated by server when new record is created
    // this is not the same as the MongoDB ObjectId
    // this is used to identify the food item in the database
    // and is used to create the food item in the database

    name: {
        type: String,
        required: true,
    },
    description: {
        type: String,
        required: true,
    },
    image: {
        type: String,
        required: true,
    },
    categoryId: {
        type: mongoose.Schema.Types.ObjectId,
        required: true,
    },
    cuisineId: {
        type: mongoose.Schema.Types.ObjectId,
        required: true,
    },
    isVeg: {
        type: Boolean,
        required: true,
    },
    isActive: {
        type: Boolean,
        default: true,
    },
    createdTs: {
        type: Date,
        default: new Date(),
    },
    updatedTs: {
        type: Date,
        default: new Date(),
    }
});

const FooditemModel = mongoose.model('Fooditems', fooditemSchema);

module.exports = FooditemModel;